GROUP=io.github.zphrio
VERSION_NAME=1.0

POM_NAME=adhan-java
POM_ARTIFACT_ID=adhan-java
POM_DESCRIPTION=High precision Islamic prayer time library for Java
POM_INCEPTION_YEAR=2026
POM_URL=https://github.com/zphrio/adhan-java/

POM_LICENSE_NAME=MIT
POM_LICENSE_URL=https://opensource.org/licenses/MIT
POM_LICENSE_DIST=repo

POM_SCM_URL=https://github.com/zphrio/adhan-java/
POM_SCM_CONNECTION=scm:git:git://github.com/zphrio/adhan-java.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/zphrio/adhan-java.git

POM_DEVELOPER_ID=zphrio
POM_DEVELOPER_NAME=Zayed Alabbad
POM_DEVELOPER_URL=https://github.com/zphrio/
